[package]
name = "rpi-temp-fan-pwm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
rppal = "0.22.1"
snafu = "0.8.5"
