# https://github.com/sagiegurari/cargo-make

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.all-dev]
dependencies = [
    "format",
    "lint",
    "build",
    "test"
]


[tasks.cog-bump]
command = "cog"
args = ["bump", "--auto"]


[tasks.do-release]
dependencies = [
    "cog-bump",
]
